name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        # go-version: 1.17
        go-version: 1.16

    - name: Tidy
      run: cd app/backend && go mod tidy
    - name: Build
      # run: go build -v ./...
      run: cd app/backend && go build -o dist/app src/main.go

    - name: Test
      # run: go test -v ./...
      run: cd app/backend && go test -v ./src/...
